dist: xenial
language: python
python:
- '3.6'
cache:
  pip: true
env:
- DEPLOY_PYPI="true"
deploy:
  matrix:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/bundles/*"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  - provider: pypi
    user: 2bndy5
    password:
      secure: Rn5kjXiWeG8Qlex6ZdS8sontrTaYZIFt7O/6xP5mfp9n1uxyumzteN5llI6wCDxlDPMtsvfhbWMvK+zeGJUQLyzK52t5IIWo0vULbIIZRdaJ74Djsnxh43i8siYSlNu+4VCpqfdR5o9wEU8lte53RtST9DLLk1NgokPBrRuC1uj5WGHnbVaq24QjWpDYWFw+/MtFSSbBGDPDf/s1qJnsH4LSUF95hnl1hwEyk7+0euy3wcpmDB1gqC+RRmwACiVP0qXpIroEVjRvKMjq9C0VvUQowZ/urt4isWVYrO/JT+WA2/BcLep1ep7zF46YUob1HxUqgsx04xx4y8EBbwc6yuI8xbukBIqk6DzEaFZAn5b/JFRzAOT9hbg3WYjkmtSQ2WIfb++ThnadfPhgQegrD0yBhb8UsQZeOXVWUEeSwQm4p1qQYeftfptLCkdGkamOzaijABYH8g4Rsj3oisqRMBkKE55lMcX/quggchSvASi/A/OhR/LcNX58m5yOu4rEWxdh6UEV+X7zpWDdqSMwYnCfAvrg+J7SjOYVmrfefCKRbu5I1MHO9tivZ33izUKxYeko5AexAqkoD+y1Na2PfMZi2tv2XtqPBdA6mzQwnWLNNp+xjSgntUc5VS97CpcJ1YDWiXdmhXVwy3bq1+cyN3npsAKeEySowDgtJWsS5yo=
    on:
      tags: true
      condition: $DEPLOY_PYPI = "true"
  password:
    secure: ESeHy6taKveWs5Yy8YLzyNWKW/0etOjiZzs//Zn9jFSjjVVU3n6RCNeT6dEs6u8szu+O8fmawCY/5w4lFkkNpwm5OU0oN1EZI8wMIGYiCFQWXz56t7sKn55Ei8B0aKW3qW0+3HGrqquvcpwifBBl9CGwxgVdKKd7dTosM6DWMQ5p8T6Vvfd6SXbLdPUK0KKi26TzYYskEY3bbdmbwM+gS+dtUrhgPhItXx/BA87O5c9FGUc+VOLXt5Q7de6w1Oo5Ux9NxKXnBPQKGYrrZMwipkj3hPB0hMfLhvWVVO3aDbifn8hITs+oIkUaGrJohCbHfIHBL5tg+cHCD14LNi88zuCZDylutDlTHH4RDOs61dEz7FjGWzlRMKB27NmWirldZK8BxtBvIKGAvPxwIlXNL1C5yLiZ3acrnnLRjhNBKfrW94y93xgLRtg6MDc6nePDtl/X9nIN8y4cb1MbaTJaEHOxxd57gY1cGf/6fNYeGqyTypkhQAbJBJk+tPLr/ShoplXmcXtrFDjc3SsWt+ziujWsWpYHWR/eVZ1ODAcbB0EAMShT1BimEIri/3VJgXKh9pG7dwZM8ShL3BDtZ2xvDJ8+FQSA4WActeiXfL+gs7Engr694+UDCsPm4mYllAUBCG/7x4iDGbjGvRcZXOxBRmcF3idvu2sGZkj1hTZsW6Q=
install:
- pip install -r requirements.txt
- pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint circuitpython_mpu6050.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace
  examples/*.py)
- circuitpython-build-bundles --filename_prefix circuitpython-mpu6050 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
